name: Deploy to EC2
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Build and push Docker image
        run: |
          # Build the Docker image
          docker build -t samplee-docker-ec2 .
          
          # Tag the image
          docker tag samplee-docker-ec2:latest ${{ secrets.DOCKER_REPO_URL }}/samplee-docker-ec2:latest
          
          # Log in to Docker Hub
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          
          # Push the image to Docker Hub
          docker push ${{ secrets.DOCKER_REPO_URL }}/samplee-docker-ec2:latest


      - name: SSH into EC2 instance and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.MY_EC2_SSH_KEY }}
          script: |
            # Install Docker if not already installed
            if ! command -v docker &> /dev/null
            then
              sudo yum update -y
              sudo amazon-linux-extras install docker -y
              sudo service docker start
              sudo usermod -aG docker ec2-user
            fi
            
            # Pull the latest image and deploy
            sudo docker pull ${{ secrets.DOCKER_REPO_URL }}/samplee-docker-ec2:latest
            sudo docker stop my-node-app || true
            sudo docker rm my-node-app || true
            sudo docker run -d -p 80:80 --name my-node-app ${{ secrets.DOCKER_REPO_URL }}/samplee-docker-ec2:latest
